# Generated by Django 5.2.2 on 2025-06-15 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmllibrarytext',
            options={'ordering': ('parent', 'language'), 'verbose_name': 'HTML Library Text', 'verbose_name_plural': 'HTML Library Texts'},
        ),
        migrations.AlterModelOptions(
            name='htmllibraryversion',
            options={'ordering': ['parent', '-version'], 'verbose_name': 'HTML Library Version', 'verbose_name_plural': 'HTML Library Versions'},
        ),
        migrations.AddField(
            model_name='htmllibraryversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='htmllibraryversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='htmllibraryversion',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='htmllibraryversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
