# Generated by Django 5.2.2 on 2025-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=100, unique=True, verbose_name='Domain Name'),
        ),
    ]
