# Generated by Django 5.2.2 on 2025-06-13 04:07

import django.db.models.deletion
import openbook.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLLibrary',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('organization', models.CharField(max_length=100, validators=[openbook.core.validators.validate_library_name_part], verbose_name='Organization')),
                ('name', models.CharField(max_length=100, validators=[openbook.core.validators.validate_library_name_part], verbose_name='Name')),
                ('version', models.CharField(max_length=50, validators=[openbook.core.validators.validate_version_number], verbose_name='Version')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='Author')),
                ('license', models.CharField(blank=True, default='', max_length=50, verbose_name='License')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('coderepo', models.URLField(blank=True, default='', verbose_name='Code Repository')),
                ('bugtracker', models.URLField(blank=True, default='', verbose_name='Bug Tracker')),
                ('dependencies', models.JSONField(blank=True, default=None, verbose_name='Dependencies')),
                ('published', models.BooleanField(default=True, help_text='Allow other installations to download the library from this server', verbose_name='Published')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'HTML Library',
                'verbose_name_plural': 'HTML Libraries',
            },
        ),
        migrations.CreateModel(
            name='HTMLComponent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tag Name')),
                ('definition', models.JSONField(blank=True, default=None, verbose_name='JSON Definition')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='openbook_core.htmllibrary')),
            ],
            options={
                'verbose_name': 'HTML Component',
                'verbose_name_plural': 'HTML Components',
            },
        ),
        migrations.CreateModel(
            name='HTMLLibraryText',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('text_format', models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=10, verbose_name='Text Format')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='openbook_core.htmllibrary')),
            ],
            options={
                'verbose_name': 'HTML Library: Translated Text',
                'verbose_name_plural': 'HTML Library: Translated Texts',
                'ordering': ('parent', 'language'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HTMLComponentText',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('text_format', models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=10, verbose_name='Text Format')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='openbook_core.htmlcomponent')),
            ],
            options={
                'verbose_name': 'HTML Component: Translated Text',
                'verbose_name_plural': 'HTML Component: Translated Texts',
                'ordering': ('parent', 'language'),
                'abstract': False,
                'indexes': [models.Index(fields=['parent', 'language'], name='openbook_co_parent__6a734a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='htmllibrary',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'version'), name='unique_library_version'),
        ),
        migrations.AddConstraint(
            model_name='htmlcomponent',
            constraint=models.UniqueConstraint(fields=('library', 'tag_name'), name='unique_html_component'),
        ),
        migrations.AddIndex(
            model_name='htmllibrarytext',
            index=models.Index(fields=['parent', 'language'], name='openbook_co_parent__40589d_idx'),
        ),
    ]
