# Generated by Django 5.2.2 on 2025-06-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0002_alter_htmllibrarytext_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmllibrary',
            name='readme',
            field=models.TextField(blank=True, verbose_name='Read Me'),
        ),
        migrations.AddField(
            model_name='htmllibrary',
            name='text_format',
            field=models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=10, verbose_name='Text Format'),
        ),
    ]
