# Generated by Django 5.2.2 on 2025-06-15 15:18

import openbook.core.models.mixins.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0003_htmllibrary_readme_htmllibrary_text_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmllibraryversion',
            name='file_data',
            field=models.FileField(blank=True, upload_to=openbook.core.models.mixins.file.FileUploadMixin._calc_file_path, verbose_name='File Data'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_data',
            field=models.FileField(blank=True, upload_to=openbook.core.models.mixins.file.FileUploadMixin._calc_file_path, verbose_name='File Data'),
        ),
    ]
