# Generated by Django 5.2.2 on 2025-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_core', '0004_alter_htmllibraryversion_file_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmllibraryversion',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
    ]
