/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CurrentUserRead,
} from '../models/index';
import {
    CurrentUserReadFromJSON,
    CurrentUserReadToJSON,
} from '../models/index';

/**
 * 
 */
export class CurrentUserApi extends runtime.BaseAPI {

    /**
     * Returns the currently authenticated user or a fallback response.
     * Retrieve
     */
    async authCurrentUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurrentUserRead>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/auth/current_user/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CurrentUserReadFromJSON));
    }

    /**
     * Returns the currently authenticated user or a fallback response.
     * Retrieve
     */
    async authCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurrentUserRead>> {
        const response = await this.authCurrentUserRaw(initOverrides);
        return await response.value();
    }

}
