# Generated by Django 5.2.1 on 2025-06-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_ui_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlcomponent_t',
            options={'ordering': ('parent', 'language'), 'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AlterModelOptions(
            name='library_t',
            options={'ordering': ('parent', 'language'), 'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
    ]
