# Generated by Django 5.2.1 on 2025-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_ui_library', '0002_alter_htmlcomponent_t_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='library',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
    ]
