# Generated by Django 5.2.1 on 2025-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_course', '0002_alter_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
    ]
