# Generated by Django 5.0.8 on 2025-01-21 12:42

import django.db.models.deletion
import openbook.library_manager.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openbook_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('name', models.CharField(max_length=100, validators=[openbook.library_manager.validators.validate_library_name], verbose_name='Name')),
                ('version', models.CharField(max_length=50, validators=[openbook.library_manager.validators.validate_version_number], verbose_name='Version')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='Author')),
                ('license', models.CharField(blank=True, default='', max_length=50, verbose_name='License')),
                ('website', models.URLField(blank=True, default='', help_text='Website with documentation', verbose_name='Website')),
                ('coderepo', models.URLField(blank=True, default='', help_text='Code repository', verbose_name='Source Code')),
                ('bugtracker', models.URLField(blank=True, default='', verbose_name='Bug Tracker')),
                ('required', models.BooleanField(default=False, help_text='Required libraries will always be included in each textbook', verbose_name='Required')),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='HTMLComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('htmltag', models.CharField(max_length=100, verbose_name='HTML Tag')),
                ('definition', models.TextField(blank=True, default='', verbose_name='JSON Definition')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_library_manager.library', verbose_name='Library')),
            ],
            options={
                'verbose_name': 'HTML Component',
                'verbose_name_plural': 'HTML Components',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('dependency', models.CharField(max_length=100, validators=[openbook.library_manager.validators.validate_library_name], verbose_name='Name')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_library_manager.library', verbose_name='Library')),
            ],
            options={
                'verbose_name': 'Dependency',
                'verbose_name_plural': 'Dependencies',
            },
        ),
        migrations.CreateModel(
            name='Library_T',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='openbook_library_manager.library')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['parent', 'language'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('publish', models.BooleanField(help_text='Allow other installations to download the library from this server.', verbose_name='Publish')),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_library_manager.library', verbose_name='Library')),
                ('modified_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Published Library',
                'verbose_name_plural': 'Published Libraries',
            },
        ),
        migrations.CreateModel(
            name='HTMLComponent_T',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='openbook_library_manager.htmlcomponent')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['parent', 'language'],
                'abstract': False,
                'indexes': [models.Index(fields=['parent', 'language'], name='openbook_li_parent__788550_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(models.F('name'), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.UniqueConstraint(models.F('library'), models.F('dependency'), name='unique_library_dependency'),
        ),
        migrations.AddIndex(
            model_name='library_t',
            index=models.Index(fields=['parent', 'language'], name='openbook_li_parent__201249_idx'),
        ),
    ]
