# Generated by Django 5.2.1 on 2025-06-05 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('openbook_auth', '0001_initial'),
        ('openbook_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontext',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language'),
        ),
        migrations.AddField(
            model_name='permissiontext',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='auth.permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='role',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='role',
            name='scope_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Scope Type'),
        ),
        migrations.AddField(
            model_name='enrollmentmethod',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_methods', to='openbook_auth.role'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='openbook_auth.role'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='access_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignment', to='openbook_auth.accessrequest'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='enrollment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='openbook_auth.enrollmentmethod'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='openbook_auth.role'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='scope_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Scope Type'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='allowedrolepermission',
            index=models.Index(fields=['scope_type'], name='openbook_au_scope_t_8496a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='allowedrolepermission',
            constraint=models.UniqueConstraint(fields=('scope_type', 'permission'), name='unique_allowed_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='anonymouspermission',
            constraint=models.UniqueConstraint(fields=('permission',), name='unique_anonymous_permission'),
        ),
        migrations.AddIndex(
            model_name='permissiontext',
            index=models.Index(fields=['parent', 'language'], name='openbook_au_parent__3c9485_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissiontext',
            constraint=models.UniqueConstraint(fields=('parent', 'language'), name='unique_PermissionTextranslation'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['scope_type', 'scope_uuid', 'slug'], name='openbook_au_scope_t_263430_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_uuid', 'slug'), name='unique_scope_slug'),
        ),
        migrations.AddIndex(
            model_name='enrollmentmethod',
            index=models.Index(fields=['scope_type', 'scope_uuid', 'role'], name='openbook_au_scope_t_6ece9a_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['scope_type', 'scope_uuid', 'role'], name='openbook_au_scope_t_f1d834_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['scope_type', 'scope_uuid', 'role', 'user'], name='openbook_au_scope_t_9e5d52_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user'], name='openbook_au_user_id_8e9382_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_uuid', 'role', 'user'), name='unique_role_assignment'),
        ),
    ]
