# Generated by Django 5.2.2 on 2025-06-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0002_initial'),
        ('openbook_core', '0001_initial'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupGroupAssignment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('text_format', models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=10, verbose_name='Text Format')),
                ('site', models.ForeignKey(blank=True, help_text='Leave blank for all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbook_core.site')),
                ('social_app', models.ForeignKey(blank=True, help_text='Leave blank for local accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='socialaccount.socialapp')),
                ('user_groups', models.ManyToManyField(related_name='+', to='openbook_auth.group')),
            ],
            options={
                'verbose_name': 'Group Assignment on Signup',
                'verbose_name_plural': 'Group Assignments on Signup',
            },
        ),
        migrations.CreateModel(
            name='SecurityAssertion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='Name of the scope or assertion', max_length=255, verbose_name='Name')),
                ('value', models.CharField(blank=True, help_text='Value of the assertion', max_length=255, null=True, verbose_name='Value')),
                ('match_strategy', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('starts-with', 'Starts With'), ('ends-with', 'Ends With'), ('regex', 'Regular Expression'), ('any', 'Any Value')], default='exact', verbose_name='Match Strategy')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='openbook_auth.signupgroupassignment')),
            ],
            options={
                'verbose_name': 'Identity Assertion',
                'verbose_name_plural': 'Identity Assertions',
            },
        ),
    ]
