# Generated by Django 5.2.2 on 2025-06-09 17:10

import django.db.models.deletion
import openbook.auth.models.auth_config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0002_initial'),
        ('openbook_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('local_signup_allowed', models.BooleanField(default=True, help_text='This only affects registration of local users without social authentication or federated identities.', verbose_name='Local Sign-Up Allowed')),
                ('signup_email_suffix', models.CharField(blank=True, help_text='This limits local user registration to e-mail addresses ending with a given suffix.', verbose_name='E-Mail Suffix')),
                ('logout_next_url', models.CharField(default='/', help_text='Link on the confirmation page shown after logout.', verbose_name='Next URL after logout')),
                ('signup_image', models.FileField(blank=True, null=True, upload_to=openbook.auth.models.auth_config.AuthConfig._calc_file_path, verbose_name='Sign-Up Page')),
                ('login_image', models.FileField(blank=True, null=True, upload_to=openbook.auth.models.auth_config.AuthConfig._calc_file_path, verbose_name='Login Page')),
                ('logout_image', models.FileField(blank=True, null=True, upload_to=openbook.auth.models.auth_config.AuthConfig._calc_file_path, verbose_name='Logout Page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_settings', to='openbook_core.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Authentication Settings',
                'verbose_name_plural': 'Authentication Settings',
                'constraints': [models.UniqueConstraint(fields=('site',), name='unique_auth_settings_site')],
            },
        ),
        migrations.CreateModel(
            name='AuthConfigText',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('logout_next_text', models.CharField(max_length=255, verbose_name='Link Text after Logout')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_core.language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='openbook_auth.authconfig')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ('parent', 'language'),
                'abstract': False,
                'indexes': [models.Index(fields=['parent', 'language'], name='openbook_au_parent__c7182c_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'language'), name='unique_auth_config_translation')],
            },
        ),
    ]
