# Generated by Django 5.2.1 on 2025-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('openbook_auth', '0003_alter_enrollmentmethod_options_and_more'),
        ('openbook_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission_t',
            options={'ordering': ('parent', 'language'), 'verbose_name': 'Translated Permission', 'verbose_name_plural': 'Translated Permissions'},
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='assignment_method',
            field=models.CharField(choices=[('manual', 'Manual Assignment'), ('self-enrollment', 'Self-Enrollment'), ('access-request', 'Access Request')], default='self-enrollment', max_length=20, verbose_name='Assignment Method'),
        ),
        migrations.AddConstraint(
            model_name='permission_t',
            constraint=models.UniqueConstraint(fields=('parent', 'language'), name='unique_permission_translation'),
        ),
    ]
