# Generated by Django 5.2.2 on 2025-06-12 03:53

import django.db.models.deletion
import openbook.auth.models.auth_token
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0003_signupgroupassignment_securityassertion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date and time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('text_format', models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=10, verbose_name='Text Format')),
                ('token', models.CharField(default=openbook.auth.models.auth_token.generate_token, max_length=64, unique=True, verbose_name='Token')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Token',
                'verbose_name_plural': 'Authentication Tokens',
                'permissions': (('manage_own_authtoken', 'Can mange own authentication tokens'),),
                'indexes': [models.Index(fields=['user'], name='openbook_au_user_id_83f6b9_idx'), models.Index(fields=['token'], name='openbook_au_token_fbe9e2_idx')],
            },
        ),
    ]
