# Generated by Django 5.2.1 on 2025-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0004_alter_permission_t_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_t',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
