# Generated by Django 5.2.1 on 2025-06-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('openbook_auth', '0005_alter_permission_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPermission',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.permission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Anonymous Permission',
                'verbose_name_plural': 'Anonymous Permissions',
            },
        ),
    ]
