# Generated by Django 5.2.1 on 2025-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('openbook_auth', '0006_anonymouspermission'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anonymouspermission',
            constraint=models.UniqueConstraint(fields=('permission',), name='unique_anonymous_permission'),
        ),
    ]
