# Generated by Django 5.2.1 on 2025-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('openbook_auth', '0007_anonymouspermission_unique_anonymous_permission'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allowedrolepermission',
            constraint=models.UniqueConstraint(fields=('scope_type', 'permission'), name='unique_allowed_role_permission'),
        ),
    ]
