# Generated by Django 5.2.1 on 2025-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0008_allowedrolepermission_unique_allowed_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='enrollmentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='enrollmentmethod',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At'),
        ),
    ]
