/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRead } from './UserRead';
import {
    UserReadFromJSON,
    UserReadFromJSONTyped,
    UserReadToJSON,
    UserReadToJSONTyped,
} from './UserRead';
import type { AccessRequestDurationPeriod } from './AccessRequestDurationPeriod';
import {
    AccessRequestDurationPeriodFromJSON,
    AccessRequestDurationPeriodFromJSONTyped,
    AccessRequestDurationPeriodToJSON,
    AccessRequestDurationPeriodToJSONTyped,
} from './AccessRequestDurationPeriod';
import type { RoleRead } from './RoleRead';
import {
    RoleReadFromJSON,
    RoleReadFromJSONTyped,
    RoleReadToJSON,
    RoleReadToJSONTyped,
} from './RoleRead';
import type { DecisionEnum } from './DecisionEnum';
import {
    DecisionEnumFromJSON,
    DecisionEnumFromJSONTyped,
    DecisionEnumToJSON,
    DecisionEnumToJSONTyped,
} from './DecisionEnum';

/**
 * Full list of fields for retrieving a single access request.
 * @export
 * @interface AccessRequest
 */
export interface AccessRequest {
    /**
     * 
     * @type {string}
     * @memberof AccessRequest
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof AccessRequest
     */
    scopeType: string;
    /**
     * 
     * @type {string}
     * @memberof AccessRequest
     */
    scopeUuid: string;
    /**
     * 
     * @type {RoleRead}
     * @memberof AccessRequest
     */
    readonly role: RoleRead;
    /**
     * 
     * @type {string}
     * @memberof AccessRequest
     */
    roleSlug: string;
    /**
     * 
     * @type {UserRead}
     * @memberof AccessRequest
     */
    readonly user: UserRead;
    /**
     * User name
     * @type {string}
     * @memberof AccessRequest
     */
    userUsername: string;
    /**
     * 
     * @type {Date}
     * @memberof AccessRequest
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof AccessRequest
     */
    durationValue?: number;
    /**
     * 
     * @type {AccessRequestDurationPeriod}
     * @memberof AccessRequest
     */
    durationPeriod?: AccessRequestDurationPeriod;
    /**
     * 
     * @type {DecisionEnum}
     * @memberof AccessRequest
     */
    decision?: DecisionEnum;
    /**
     * 
     * @type {Date}
     * @memberof AccessRequest
     */
    readonly decisionDate: Date | null;
    /**
     * 
     * @type {UserRead}
     * @memberof AccessRequest
     */
    readonly createdBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof AccessRequest
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {UserRead}
     * @memberof AccessRequest
     */
    readonly modifiedBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof AccessRequest
     */
    readonly modifiedAt: Date;
}



/**
 * Check if a given object implements the AccessRequest interface.
 */
export function instanceOfAccessRequest(value: object): value is AccessRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('roleSlug' in value) || value['roleSlug'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('userUsername' in value) || value['userUsername'] === undefined) return false;
    if (!('decisionDate' in value) || value['decisionDate'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function AccessRequestFromJSON(json: any): AccessRequest {
    return AccessRequestFromJSONTyped(json, false);
}

export function AccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'role': RoleReadFromJSON(json['role']),
        'roleSlug': json['role_slug'],
        'user': UserReadFromJSON(json['user']),
        'userUsername': json['user_username'],
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'durationValue': json['duration_value'] == null ? undefined : json['duration_value'],
        'durationPeriod': json['duration_period'] == null ? undefined : AccessRequestDurationPeriodFromJSON(json['duration_period']),
        'decision': json['decision'] == null ? undefined : DecisionEnumFromJSON(json['decision']),
        'decisionDate': (json['decision_date'] == null ? null : new Date(json['decision_date'])),
        'createdBy': UserReadFromJSON(json['created_by']),
        'createdAt': (new Date(json['created_at'])),
        'modifiedBy': UserReadFromJSON(json['modified_by']),
        'modifiedAt': (new Date(json['modified_at'])),
    };
}

export function AccessRequestToJSON(json: any): AccessRequest {
    return AccessRequestToJSONTyped(json, false);
}

export function AccessRequestToJSONTyped(value?: Omit<AccessRequest, 'id'|'role'|'user'|'decision_date'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'role_slug': value['roleSlug'],
        'user_username': value['userUsername'],
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'duration_value': value['durationValue'],
        'duration_period': AccessRequestDurationPeriodToJSON(value['durationPeriod']),
        'decision': DecisionEnumToJSON(value['decision']),
    };
}

