/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentUserResponse
 */
export interface CurrentUserResponse {
    /**
     * Username
     * @type {string}
     * @memberof CurrentUserResponse
     */
    username: string;
    /**
     * First Name
     * @type {string}
     * @memberof CurrentUserResponse
     */
    firstName: string;
    /**
     * Last Name
     * @type {string}
     * @memberof CurrentUserResponse
     */
    lastName: string;
    /**
     * Administrative User
     * @type {boolean}
     * @memberof CurrentUserResponse
     */
    isStaff: boolean;
    /**
     * Logged-in User
     * @type {boolean}
     * @memberof CurrentUserResponse
     */
    isAuthenticated: boolean;
}

/**
 * Check if a given object implements the CurrentUserResponse interface.
 */
export function instanceOfCurrentUserResponse(value: object): value is CurrentUserResponse {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('isStaff' in value) || value['isStaff'] === undefined) return false;
    if (!('isAuthenticated' in value) || value['isAuthenticated'] === undefined) return false;
    return true;
}

export function CurrentUserResponseFromJSON(json: any): CurrentUserResponse {
    return CurrentUserResponseFromJSONTyped(json, false);
}

export function CurrentUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'isStaff': json['is_staff'],
        'isAuthenticated': json['is_authenticated'],
    };
}

export function CurrentUserResponseToJSON(json: any): CurrentUserResponse {
    return CurrentUserResponseToJSONTyped(json, false);
}

export function CurrentUserResponseToJSONTyped(value?: CurrentUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'is_staff': value['isStaff'],
        'is_authenticated': value['isAuthenticated'],
    };
}

