/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User (Full Profile)
 * @export
 * @interface CurrentUserRead
 */
export interface CurrentUserRead {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof CurrentUserRead
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserRead
     */
    readonly fullName: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserRead
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserRead
     */
    lastName?: string;
    /**
     * URL for profile picture
     * @type {string}
     * @memberof CurrentUserRead
     */
    readonly profilePicture: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserRead
     */
    readonly description: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserRead
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUserRead
     */
    readonly isAuthenticated: string;
}

/**
 * Check if a given object implements the CurrentUserRead interface.
 */
export function instanceOfCurrentUserRead(value: object): value is CurrentUserRead {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('profilePicture' in value) || value['profilePicture'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isAuthenticated' in value) || value['isAuthenticated'] === undefined) return false;
    return true;
}

export function CurrentUserReadFromJSON(json: any): CurrentUserRead {
    return CurrentUserReadFromJSONTyped(json, false);
}

export function CurrentUserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserRead {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'fullName': json['full_name'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'profilePicture': json['profile_picture'],
        'description': json['description'],
        'email': json['email'],
        'isAuthenticated': json['is_authenticated'],
    };
}

export function CurrentUserReadToJSON(json: any): CurrentUserRead {
    return CurrentUserReadToJSONTyped(json, false);
}

export function CurrentUserReadToJSONTyped(value?: Omit<CurrentUserRead, 'full_name'|'profile_picture'|'description'|'is_authenticated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
    };
}

