/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleRead } from './RoleRead';
import {
    RoleReadFromJSON,
    RoleReadFromJSONTyped,
    RoleReadToJSON,
    RoleReadToJSONTyped,
} from './RoleRead';

/**
 * Very short overview of only the very most important enrollment method fields to
 * be embedded in parent models (with role).
 * @export
 * @interface EnrollmentMethodWithRoleRead
 */
export interface EnrollmentMethodWithRoleRead {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethodWithRoleRead
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethodWithRoleRead
     */
    readonly name: string;
    /**
     * 
     * @type {RoleRead}
     * @memberof EnrollmentMethodWithRoleRead
     */
    readonly role: RoleRead;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMethodWithRoleRead
     */
    readonly isActive: boolean;
}

/**
 * Check if a given object implements the EnrollmentMethodWithRoleRead interface.
 */
export function instanceOfEnrollmentMethodWithRoleRead(value: object): value is EnrollmentMethodWithRoleRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function EnrollmentMethodWithRoleReadFromJSON(json: any): EnrollmentMethodWithRoleRead {
    return EnrollmentMethodWithRoleReadFromJSONTyped(json, false);
}

export function EnrollmentMethodWithRoleReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentMethodWithRoleRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'role': RoleReadFromJSON(json['role']),
        'isActive': json['is_active'],
    };
}

export function EnrollmentMethodWithRoleReadToJSON(json: any): EnrollmentMethodWithRoleRead {
    return EnrollmentMethodWithRoleReadToJSONTyped(json, false);
}

export function EnrollmentMethodWithRoleReadToJSONTyped(value?: Omit<EnrollmentMethodWithRoleRead, 'id'|'name'|'role'|'is_active'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

