/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';
import type { UserRead } from './UserRead';
import {
    UserReadFromJSON,
    UserReadFromJSONTyped,
    UserReadToJSON,
    UserReadToJSONTyped,
} from './UserRead';
import type { AccessRequestDurationPeriod } from './AccessRequestDurationPeriod';
import {
    AccessRequestDurationPeriodFromJSON,
    AccessRequestDurationPeriodFromJSONTyped,
    AccessRequestDurationPeriodToJSON,
    AccessRequestDurationPeriodToJSONTyped,
} from './AccessRequestDurationPeriod';
import type { RoleRead } from './RoleRead';
import {
    RoleReadFromJSON,
    RoleReadFromJSONTyped,
    RoleReadToJSON,
    RoleReadToJSONTyped,
} from './RoleRead';

/**
 * Full list of fields for retrieving a single enrollment method.
 * @export
 * @interface EnrollmentMethod
 */
export interface EnrollmentMethod {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    scopeType: string;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    scopeUuid: string;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof EnrollmentMethod
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {RoleRead}
     * @memberof EnrollmentMethod
     */
    readonly role: RoleRead;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    roleSlug: string;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMethod
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentMethod
     */
    durationValue?: number;
    /**
     * 
     * @type {AccessRequestDurationPeriod}
     * @memberof EnrollmentMethod
     */
    durationPeriod?: AccessRequestDurationPeriod;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentMethod
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMethod
     */
    passphrase?: string;
    /**
     * 
     * @type {UserRead}
     * @memberof EnrollmentMethod
     */
    readonly createdBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentMethod
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {UserRead}
     * @memberof EnrollmentMethod
     */
    readonly modifiedBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentMethod
     */
    readonly modifiedAt: Date;
}



/**
 * Check if a given object implements the EnrollmentMethod interface.
 */
export function instanceOfEnrollmentMethod(value: object): value is EnrollmentMethod {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('roleSlug' in value) || value['roleSlug'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function EnrollmentMethodFromJSON(json: any): EnrollmentMethod {
    return EnrollmentMethodFromJSONTyped(json, false);
}

export function EnrollmentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'role': RoleReadFromJSON(json['role']),
        'roleSlug': json['role_slug'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'durationValue': json['duration_value'] == null ? undefined : json['duration_value'],
        'durationPeriod': json['duration_period'] == null ? undefined : AccessRequestDurationPeriodFromJSON(json['duration_period']),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'passphrase': json['passphrase'] == null ? undefined : json['passphrase'],
        'createdBy': UserReadFromJSON(json['created_by']),
        'createdAt': (new Date(json['created_at'])),
        'modifiedBy': UserReadFromJSON(json['modified_by']),
        'modifiedAt': (new Date(json['modified_at'])),
    };
}

export function EnrollmentMethodToJSON(json: any): EnrollmentMethod {
    return EnrollmentMethodToJSONTyped(json, false);
}

export function EnrollmentMethodToJSONTyped(value?: Omit<EnrollmentMethod, 'id'|'role'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'role_slug': value['roleSlug'],
        'is_active': value['isActive'],
        'duration_value': value['durationValue'],
        'duration_period': AccessRequestDurationPeriodToJSON(value['durationPeriod']),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'passphrase': value['passphrase'],
    };
}

