/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Nested
 */
export interface Nested {
    /**
     * 
     * @type {number}
     * @memberof Nested
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Nested
     */
    appLabel: string;
    /**
     * 
     * @type {string}
     * @memberof Nested
     */
    model: string;
}

/**
 * Check if a given object implements the Nested interface.
 */
export function instanceOfNested(value: object): value is Nested {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appLabel' in value) || value['appLabel'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function NestedFromJSON(json: any): Nested {
    return NestedFromJSONTyped(json, false);
}

export function NestedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nested {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appLabel': json['app_label'],
        'model': json['model'],
    };
}

export function NestedToJSON(json: any): Nested {
    return NestedToJSONTyped(json, false);
}

export function NestedToJSONTyped(value?: Omit<Nested, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_label': value['appLabel'],
        'model': value['model'],
    };
}

