/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionT } from './PermissionT';
import {
    PermissionTFromJSON,
    PermissionTFromJSONTyped,
    PermissionTToJSON,
    PermissionTToJSONTyped,
} from './PermissionT';

/**
 * 
 * @export
 * @interface PaginatedPermissionTList
 */
export interface PaginatedPermissionTList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPermissionTList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPermissionTList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPermissionTList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PermissionT>}
     * @memberof PaginatedPermissionTList
     */
    results: Array<PermissionT>;
}

/**
 * Check if a given object implements the PaginatedPermissionTList interface.
 */
export function instanceOfPaginatedPermissionTList(value: object): value is PaginatedPermissionTList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedPermissionTListFromJSON(json: any): PaginatedPermissionTList {
    return PaginatedPermissionTListFromJSONTyped(json, false);
}

export function PaginatedPermissionTListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPermissionTList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(PermissionTFromJSON)),
    };
}

export function PaginatedPermissionTListToJSON(json: any): PaginatedPermissionTList {
    return PaginatedPermissionTListToJSONTyped(json, false);
}

export function PaginatedPermissionTListToJSONTyped(value?: PaginatedPermissionTList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(PermissionTToJSON)),
    };
}

