/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleAssignmentList } from './RoleAssignmentList';
import {
    RoleAssignmentListFromJSON,
    RoleAssignmentListFromJSONTyped,
    RoleAssignmentListToJSON,
    RoleAssignmentListToJSONTyped,
} from './RoleAssignmentList';

/**
 * 
 * @export
 * @interface PaginatedRoleAssignmentListList
 */
export interface PaginatedRoleAssignmentListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRoleAssignmentListList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRoleAssignmentListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRoleAssignmentListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RoleAssignmentList>}
     * @memberof PaginatedRoleAssignmentListList
     */
    results: Array<RoleAssignmentList>;
}

/**
 * Check if a given object implements the PaginatedRoleAssignmentListList interface.
 */
export function instanceOfPaginatedRoleAssignmentListList(value: object): value is PaginatedRoleAssignmentListList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRoleAssignmentListListFromJSON(json: any): PaginatedRoleAssignmentListList {
    return PaginatedRoleAssignmentListListFromJSONTyped(json, false);
}

export function PaginatedRoleAssignmentListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRoleAssignmentListList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RoleAssignmentListFromJSON)),
    };
}

export function PaginatedRoleAssignmentListListToJSON(json: any): PaginatedRoleAssignmentListList {
    return PaginatedRoleAssignmentListListToJSONTyped(json, false);
}

export function PaginatedRoleAssignmentListListToJSONTyped(value?: PaginatedRoleAssignmentListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RoleAssignmentListToJSON)),
    };
}

