/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaFileList } from './MediaFileList';
import {
    MediaFileListFromJSON,
    MediaFileListFromJSONTyped,
    MediaFileListToJSON,
    MediaFileListToJSONTyped,
} from './MediaFileList';

/**
 * 
 * @export
 * @interface PaginatedMediaFileListList
 */
export interface PaginatedMediaFileListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMediaFileListList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMediaFileListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMediaFileListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<MediaFileList>}
     * @memberof PaginatedMediaFileListList
     */
    results: Array<MediaFileList>;
}

/**
 * Check if a given object implements the PaginatedMediaFileListList interface.
 */
export function instanceOfPaginatedMediaFileListList(value: object): value is PaginatedMediaFileListList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedMediaFileListListFromJSON(json: any): PaginatedMediaFileListList {
    return PaginatedMediaFileListListFromJSONTyped(json, false);
}

export function PaginatedMediaFileListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMediaFileListList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(MediaFileListFromJSON)),
    };
}

export function PaginatedMediaFileListListToJSON(json: any): PaginatedMediaFileListList {
    return PaginatedMediaFileListListToJSONTyped(json, false);
}

export function PaginatedMediaFileListListToJSONTyped(value?: PaginatedMediaFileListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(MediaFileListToJSON)),
    };
}

