/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseList } from './CourseList';
import {
    CourseListFromJSON,
    CourseListFromJSONTyped,
    CourseListToJSON,
    CourseListToJSONTyped,
} from './CourseList';

/**
 * 
 * @export
 * @interface PaginatedCourseListList
 */
export interface PaginatedCourseListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCourseListList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CourseList>}
     * @memberof PaginatedCourseListList
     */
    results: Array<CourseList>;
}

/**
 * Check if a given object implements the PaginatedCourseListList interface.
 */
export function instanceOfPaginatedCourseListList(value: object): value is PaginatedCourseListList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCourseListListFromJSON(json: any): PaginatedCourseListList {
    return PaginatedCourseListListFromJSONTyped(json, false);
}

export function PaginatedCourseListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCourseListList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CourseListFromJSON)),
    };
}

export function PaginatedCourseListListToJSON(json: any): PaginatedCourseListList {
    return PaginatedCourseListListToJSONTyped(json, false);
}

export function PaginatedCourseListListToJSONTyped(value?: PaginatedCourseListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CourseListToJSON)),
    };
}

