/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessRequestList } from './AccessRequestList';
import {
    AccessRequestListFromJSON,
    AccessRequestListFromJSONTyped,
    AccessRequestListToJSON,
    AccessRequestListToJSONTyped,
} from './AccessRequestList';

/**
 * 
 * @export
 * @interface PaginatedAccessRequestListList
 */
export interface PaginatedAccessRequestListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAccessRequestListList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccessRequestListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccessRequestListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AccessRequestList>}
     * @memberof PaginatedAccessRequestListList
     */
    results: Array<AccessRequestList>;
}

/**
 * Check if a given object implements the PaginatedAccessRequestListList interface.
 */
export function instanceOfPaginatedAccessRequestListList(value: object): value is PaginatedAccessRequestListList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAccessRequestListListFromJSON(json: any): PaginatedAccessRequestListList {
    return PaginatedAccessRequestListListFromJSONTyped(json, false);
}

export function PaginatedAccessRequestListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAccessRequestListList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AccessRequestListFromJSON)),
    };
}

export function PaginatedAccessRequestListListToJSON(json: any): PaginatedAccessRequestListList {
    return PaginatedAccessRequestListListToJSONTyped(json, false);
}

export function PaginatedAccessRequestListListToJSONTyped(value?: PaginatedAccessRequestListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AccessRequestListToJSON)),
    };
}

