/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTML Library Version
 * @export
 * @interface PatchedHTMLLibraryVersion
 */
export interface PatchedHTMLLibraryVersion {
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    parent?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    version?: string;
    /**
     * 
     * @type {any}
     * @memberof PatchedHTMLLibraryVersion
     */
    dependencies?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly frontendUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    fileData?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    fileName?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedHTMLLibraryVersion
     */
    fileSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    mimeType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly components?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedHTMLLibraryVersion
     */
    readonly modifiedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedHTMLLibraryVersion interface.
 */
export function instanceOfPatchedHTMLLibraryVersion(value: object): value is PatchedHTMLLibraryVersion {
    return true;
}

export function PatchedHTMLLibraryVersionFromJSON(json: any): PatchedHTMLLibraryVersion {
    return PatchedHTMLLibraryVersionFromJSONTyped(json, false);
}

export function PatchedHTMLLibraryVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedHTMLLibraryVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'version': json['version'] == null ? undefined : json['version'],
        'dependencies': json['dependencies'] == null ? undefined : json['dependencies'],
        'frontendUrl': json['frontend_url'] == null ? undefined : json['frontend_url'],
        'fileData': json['file_data'] == null ? undefined : json['file_data'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'fileSize': json['file_size'] == null ? undefined : json['file_size'],
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'components': json['components'] == null ? undefined : json['components'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedHTMLLibraryVersionToJSON(json: any): PatchedHTMLLibraryVersion {
    return PatchedHTMLLibraryVersionToJSONTyped(json, false);
}

export function PatchedHTMLLibraryVersionToJSONTyped(value?: Omit<PatchedHTMLLibraryVersion, 'id'|'frontend_url'|'components'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parent': value['parent'],
        'version': value['version'],
        'dependencies': value['dependencies'],
        'file_data': value['fileData'],
        'file_name': value['fileName'],
        'file_size': value['fileSize'],
        'mime_type': value['mimeType'],
    };
}

