/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * HTML Library
 * @export
 * @interface PatchedHTMLLibrary
 */
export interface PatchedHTMLLibrary {
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    readonly fqn?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    license?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    coderepo?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    bugtracker?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    readme?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof PatchedHTMLLibrary
     */
    textFormat?: TextFormatEnum;
    /**
     * Allow other installations to download the library from this server
     * @type {boolean}
     * @memberof PatchedHTMLLibrary
     */
    published?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedHTMLLibrary
     */
    readonly translations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedHTMLLibrary
     */
    readonly versions?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedHTMLLibrary
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibrary
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedHTMLLibrary
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedHTMLLibrary interface.
 */
export function instanceOfPatchedHTMLLibrary(value: object): value is PatchedHTMLLibrary {
    return true;
}

export function PatchedHTMLLibraryFromJSON(json: any): PatchedHTMLLibrary {
    return PatchedHTMLLibraryFromJSONTyped(json, false);
}

export function PatchedHTMLLibraryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedHTMLLibrary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fqn': json['fqn'] == null ? undefined : json['fqn'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'name': json['name'] == null ? undefined : json['name'],
        'author': json['author'] == null ? undefined : json['author'],
        'license': json['license'] == null ? undefined : json['license'],
        'website': json['website'] == null ? undefined : json['website'],
        'coderepo': json['coderepo'] == null ? undefined : json['coderepo'],
        'bugtracker': json['bugtracker'] == null ? undefined : json['bugtracker'],
        'readme': json['readme'] == null ? undefined : json['readme'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'published': json['published'] == null ? undefined : json['published'],
        'translations': json['translations'] == null ? undefined : json['translations'],
        'versions': json['versions'] == null ? undefined : json['versions'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedHTMLLibraryToJSON(json: any): PatchedHTMLLibrary {
    return PatchedHTMLLibraryToJSONTyped(json, false);
}

export function PatchedHTMLLibraryToJSONTyped(value?: Omit<PatchedHTMLLibrary, 'id'|'fqn'|'translations'|'versions'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'name': value['name'],
        'author': value['author'],
        'license': value['license'],
        'website': value['website'],
        'coderepo': value['coderepo'],
        'bugtracker': value['bugtracker'],
        'readme': value['readme'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'published': value['published'],
    };
}

