/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTML Library Text
 * @export
 * @interface PatchedHTMLLibraryText
 */
export interface PatchedHTMLLibraryText {
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryText
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryText
     */
    parent?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryText
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLLibraryText
     */
    shortDescription?: string;
}

/**
 * Check if a given object implements the PatchedHTMLLibraryText interface.
 */
export function instanceOfPatchedHTMLLibraryText(value: object): value is PatchedHTMLLibraryText {
    return true;
}

export function PatchedHTMLLibraryTextFromJSON(json: any): PatchedHTMLLibraryText {
    return PatchedHTMLLibraryTextFromJSONTyped(json, false);
}

export function PatchedHTMLLibraryTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedHTMLLibraryText {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'language': json['language'] == null ? undefined : json['language'],
        'shortDescription': json['short_description'] == null ? undefined : json['short_description'],
    };
}

export function PatchedHTMLLibraryTextToJSON(json: any): PatchedHTMLLibraryText {
    return PatchedHTMLLibraryTextToJSONTyped(json, false);
}

export function PatchedHTMLLibraryTextToJSONTyped(value?: Omit<PatchedHTMLLibraryText, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parent': value['parent'],
        'language': value['language'],
        'short_description': value['shortDescription'],
    };
}

