/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User
 * @export
 * @interface PatchedUserRead
 */
export interface PatchedUserRead {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PatchedUserRead
     */
    username?: string;
    /**
     * Formatted name.
     * @type {string}
     * @memberof PatchedUserRead
     */
    readonly displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserRead
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserRead
     */
    lastName?: string;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof PatchedUserRead
     */
    isStaff?: boolean;
}

/**
 * Check if a given object implements the PatchedUserRead interface.
 */
export function instanceOfPatchedUserRead(value: object): value is PatchedUserRead {
    return true;
}

export function PatchedUserReadFromJSON(json: any): PatchedUserRead {
    return PatchedUserReadFromJSONTyped(json, false);
}

export function PatchedUserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserRead {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'isStaff': json['is_staff'] == null ? undefined : json['is_staff'],
    };
}

export function PatchedUserReadToJSON(json: any): PatchedUserRead {
    return PatchedUserReadToJSONTyped(json, false);
}

export function PatchedUserReadToJSONTyped(value?: Omit<PatchedUserRead, 'display_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'is_staff': value['isStaff'],
    };
}

