/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTML Component Definition
 * @export
 * @interface PatchedHTMLComponentDefinition
 */
export interface PatchedHTMLComponentDefinition {
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLComponentDefinition
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLComponentDefinition
     */
    htmlComponent?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedHTMLComponentDefinition
     */
    libraryVersion?: string;
    /**
     * 
     * @type {any}
     * @memberof PatchedHTMLComponentDefinition
     */
    definition?: any | null;
}

/**
 * Check if a given object implements the PatchedHTMLComponentDefinition interface.
 */
export function instanceOfPatchedHTMLComponentDefinition(value: object): value is PatchedHTMLComponentDefinition {
    return true;
}

export function PatchedHTMLComponentDefinitionFromJSON(json: any): PatchedHTMLComponentDefinition {
    return PatchedHTMLComponentDefinitionFromJSONTyped(json, false);
}

export function PatchedHTMLComponentDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedHTMLComponentDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'htmlComponent': json['html_component'] == null ? undefined : json['html_component'],
        'libraryVersion': json['library_version'] == null ? undefined : json['library_version'],
        'definition': json['definition'] == null ? undefined : json['definition'],
    };
}

export function PatchedHTMLComponentDefinitionToJSON(json: any): PatchedHTMLComponentDefinition {
    return PatchedHTMLComponentDefinitionToJSONTyped(json, false);
}

export function PatchedHTMLComponentDefinitionToJSONTyped(value?: Omit<PatchedHTMLComponentDefinition, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html_component': value['htmlComponent'],
        'library_version': value['libraryVersion'],
        'definition': value['definition'],
    };
}

