/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessRequestWithoutRoleRead } from './AccessRequestWithoutRoleRead';
import {
    AccessRequestWithoutRoleReadFromJSON,
    AccessRequestWithoutRoleReadFromJSONTyped,
    AccessRequestWithoutRoleReadToJSON,
    AccessRequestWithoutRoleReadToJSONTyped,
} from './AccessRequestWithoutRoleRead';
import type { UserRead } from './UserRead';
import {
    UserReadFromJSON,
    UserReadFromJSONTyped,
    UserReadToJSON,
    UserReadToJSONTyped,
} from './UserRead';
import type { EnrollmentMethodWithoutRoleRead } from './EnrollmentMethodWithoutRoleRead';
import {
    EnrollmentMethodWithoutRoleReadFromJSON,
    EnrollmentMethodWithoutRoleReadFromJSONTyped,
    EnrollmentMethodWithoutRoleReadToJSON,
    EnrollmentMethodWithoutRoleReadToJSONTyped,
} from './EnrollmentMethodWithoutRoleRead';
import type { AssignmentMethodEnum } from './AssignmentMethodEnum';
import {
    AssignmentMethodEnumFromJSON,
    AssignmentMethodEnumFromJSONTyped,
    AssignmentMethodEnumToJSON,
    AssignmentMethodEnumToJSONTyped,
} from './AssignmentMethodEnum';
import type { RoleRead } from './RoleRead';
import {
    RoleReadFromJSON,
    RoleReadFromJSONTyped,
    RoleReadToJSON,
    RoleReadToJSONTyped,
} from './RoleRead';

/**
 * Full list of fields for retrieving a single role assignment.
 * @export
 * @interface PatchedRoleAssignment
 */
export interface PatchedRoleAssignment {
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    scopeType?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    scopeUuid?: string;
    /**
     * 
     * @type {RoleRead}
     * @memberof PatchedRoleAssignment
     */
    readonly role?: RoleRead;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    roleSlug?: string;
    /**
     * 
     * @type {UserRead}
     * @memberof PatchedRoleAssignment
     */
    readonly user?: UserRead;
    /**
     * User name
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    userUsername?: string;
    /**
     * 
     * @type {AssignmentMethodEnum}
     * @memberof PatchedRoleAssignment
     */
    readonly assignmentMethod?: AssignmentMethodEnum;
    /**
     * 
     * @type {EnrollmentMethodWithoutRoleRead}
     * @memberof PatchedRoleAssignment
     */
    readonly enrollmentMethod?: EnrollmentMethodWithoutRoleRead;
    /**
     * 
     * @type {AccessRequestWithoutRoleRead}
     * @memberof PatchedRoleAssignment
     */
    readonly accessRequest?: AccessRequestWithoutRoleRead;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedRoleAssignment
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    endDate?: Date | null;
    /**
     * 
     * @type {UserRead}
     * @memberof PatchedRoleAssignment
     */
    readonly createdBy?: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {UserRead}
     * @memberof PatchedRoleAssignment
     */
    readonly modifiedBy?: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    readonly modifiedAt?: Date;
}



/**
 * Check if a given object implements the PatchedRoleAssignment interface.
 */
export function instanceOfPatchedRoleAssignment(value: object): value is PatchedRoleAssignment {
    return true;
}

export function PatchedRoleAssignmentFromJSON(json: any): PatchedRoleAssignment {
    return PatchedRoleAssignmentFromJSONTyped(json, false);
}

export function PatchedRoleAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRoleAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'scopeType': json['scope_type'] == null ? undefined : json['scope_type'],
        'scopeUuid': json['scope_uuid'] == null ? undefined : json['scope_uuid'],
        'role': json['role'] == null ? undefined : RoleReadFromJSON(json['role']),
        'roleSlug': json['role_slug'] == null ? undefined : json['role_slug'],
        'user': json['user'] == null ? undefined : UserReadFromJSON(json['user']),
        'userUsername': json['user_username'] == null ? undefined : json['user_username'],
        'assignmentMethod': json['assignment_method'] == null ? undefined : AssignmentMethodEnumFromJSON(json['assignment_method']),
        'enrollmentMethod': json['enrollment_method'] == null ? undefined : EnrollmentMethodWithoutRoleReadFromJSON(json['enrollment_method']),
        'accessRequest': json['access_request'] == null ? undefined : AccessRequestWithoutRoleReadFromJSON(json['access_request']),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'createdBy': json['created_by'] == null ? undefined : UserReadFromJSON(json['created_by']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : UserReadFromJSON(json['modified_by']),
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedRoleAssignmentToJSON(json: any): PatchedRoleAssignment {
    return PatchedRoleAssignmentToJSONTyped(json, false);
}

export function PatchedRoleAssignmentToJSONTyped(value?: Omit<PatchedRoleAssignment, 'id'|'role'|'user'|'assignment_method'|'enrollment_method'|'access_request'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'role_slug': value['roleSlug'],
        'user_username': value['userUsername'],
        'is_active': value['isActive'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

