/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * Full list of fields for retrieving a single role.
 * @export
 * @interface RoleRetrieve
 */
export interface RoleRetrieve {
    /**
     * 
     * @type {string}
     * @memberof RoleRetrieve
     */
    readonly id: string;
    /**
     * 
     * @type {number}
     * @memberof RoleRetrieve
     */
    scopeType: number;
    /**
     * 
     * @type {string}
     * @memberof RoleRetrieve
     */
    scopeUuid: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRetrieve
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRetrieve
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRetrieve
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRetrieve
     */
    textFormat?: string;
    /**
     * Low values mean less privileges. Make sure to correctly prioritize the rolls to avoid privilege escalation.
     * @type {number}
     * @memberof RoleRetrieve
     */
    priority: number;
    /**
     * 
     * @type {boolean}
     * @memberof RoleRetrieve
     */
    isActive?: boolean;
    /**
     * 
     * @type {Permission}
     * @memberof RoleRetrieve
     */
    permissions: Permission;
    /**
     * 
     * @type {number}
     * @memberof RoleRetrieve
     */
    createdBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RoleRetrieve
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof RoleRetrieve
     */
    modifiedBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RoleRetrieve
     */
    readonly modifiedAt: Date;
}

/**
 * Check if a given object implements the RoleRetrieve interface.
 */
export function instanceOfRoleRetrieve(value: object): value is RoleRetrieve {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function RoleRetrieveFromJSON(json: any): RoleRetrieve {
    return RoleRetrieveFromJSONTyped(json, false);
}

export function RoleRetrieveFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleRetrieve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : json['text_format'],
        'priority': json['priority'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'permissions': PermissionFromJSON(json['permissions']),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': (new Date(json['modified_at'])),
    };
}

export function RoleRetrieveToJSON(json: any): RoleRetrieve {
    return RoleRetrieveToJSONTyped(json, false);
}

export function RoleRetrieveToJSONTyped(value?: Omit<RoleRetrieve, 'id'|'created_at'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'text_format': value['textFormat'],
        'priority': value['priority'],
        'is_active': value['isActive'],
        'permissions': PermissionToJSON(value['permissions']),
        'created_by': value['createdBy'],
        'modified_by': value['modifiedBy'],
    };
}

