/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';
import type { UserRead } from './UserRead';
import {
    UserReadFromJSON,
    UserReadFromJSONTyped,
    UserReadToJSON,
    UserReadToJSONTyped,
} from './UserRead';
import type { PermissionRead } from './PermissionRead';
import {
    PermissionReadFromJSON,
    PermissionReadFromJSONTyped,
    PermissionReadToJSON,
    PermissionReadToJSONTyped,
} from './PermissionRead';

/**
 * Full list of fields for retrieving a single role.
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    scopeType: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    scopeUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof Role
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Role
     */
    isActive?: boolean;
    /**
     * Low values mean less privileges. Make sure to correctly prioritize the rolls to avoid privilege escalation.
     * @type {number}
     * @memberof Role
     */
    priority: number;
    /**
     * 
     * @type {Array<PermissionRead>}
     * @memberof Role
     */
    readonly permissions: Array<PermissionRead>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Role
     */
    permissionStrings: Array<string>;
    /**
     * 
     * @type {UserRead}
     * @memberof Role
     */
    readonly createdBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof Role
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {UserRead}
     * @memberof Role
     */
    readonly modifiedBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof Role
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the Role interface.
 */
export function instanceOfRole(value: object): value is Role {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('permissionStrings' in value) || value['permissionStrings'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function RoleFromJSON(json: any): Role {
    return RoleFromJSONTyped(json, false);
}

export function RoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'priority': json['priority'],
        'permissions': ((json['permissions'] as Array<any>).map(PermissionReadFromJSON)),
        'permissionStrings': json['permission_strings'],
        'createdBy': UserReadFromJSON(json['created_by']),
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': UserReadFromJSON(json['modified_by']),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function RoleToJSON(json: any): Role {
    return RoleToJSONTyped(json, false);
}

export function RoleToJSONTyped(value?: Omit<Role, 'id'|'permissions'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'is_active': value['isActive'],
        'priority': value['priority'],
        'permission_strings': value['permissionStrings'],
    };
}

