/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRead } from './UserRead';
import {
    UserReadFromJSON,
    UserReadFromJSONTyped,
    UserReadToJSON,
    UserReadToJSONTyped,
} from './UserRead';
import type { RoleRead } from './RoleRead';
import {
    RoleReadFromJSON,
    RoleReadFromJSONTyped,
    RoleReadToJSON,
    RoleReadToJSONTyped,
} from './RoleRead';

/**
 * Reduced list of fields for getting a list of role assignments.
 * @export
 * @interface RoleAssignmentList
 */
export interface RoleAssignmentList {
    /**
     * 
     * @type {string}
     * @memberof RoleAssignmentList
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignmentList
     */
    scopeType: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignmentList
     */
    readonly scopeUuid: string;
    /**
     * 
     * @type {RoleRead}
     * @memberof RoleAssignmentList
     */
    readonly role: RoleRead;
    /**
     * 
     * @type {UserRead}
     * @memberof RoleAssignmentList
     */
    readonly user: UserRead;
    /**
     * 
     * @type {boolean}
     * @memberof RoleAssignmentList
     */
    readonly isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignmentList
     */
    readonly startDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignmentList
     */
    readonly endDate: Date | null;
    /**
     * 
     * @type {UserRead}
     * @memberof RoleAssignmentList
     */
    readonly createdBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignmentList
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {UserRead}
     * @memberof RoleAssignmentList
     */
    readonly modifiedBy: UserRead;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignmentList
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the RoleAssignmentList interface.
 */
export function instanceOfRoleAssignmentList(value: object): value is RoleAssignmentList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function RoleAssignmentListFromJSON(json: any): RoleAssignmentList {
    return RoleAssignmentListFromJSONTyped(json, false);
}

export function RoleAssignmentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleAssignmentList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'role': RoleReadFromJSON(json['role']),
        'user': UserReadFromJSON(json['user']),
        'isActive': json['is_active'],
        'startDate': (json['start_date'] == null ? null : new Date(json['start_date'])),
        'endDate': (json['end_date'] == null ? null : new Date(json['end_date'])),
        'createdBy': UserReadFromJSON(json['created_by']),
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': UserReadFromJSON(json['modified_by']),
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function RoleAssignmentListToJSON(json: any): RoleAssignmentList {
    return RoleAssignmentListToJSONTyped(json, false);
}

export function RoleAssignmentListToJSONTyped(value?: Omit<RoleAssignmentList, 'id'|'scope_uuid'|'role'|'user'|'is_active'|'start_date'|'end_date'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
    };
}

