/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Update user profile
 * @export
 * @interface UserDetailsUpdate
 */
export interface UserDetailsUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserDetailsUpdate
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsUpdate
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsUpdate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsUpdate
     */
    profilePicture?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsUpdate
     */
    description?: string;
}

/**
 * Check if a given object implements the UserDetailsUpdate interface.
 */
export function instanceOfUserDetailsUpdate(value: object): value is UserDetailsUpdate {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserDetailsUpdateFromJSON(json: any): UserDetailsUpdate {
    return UserDetailsUpdateFromJSONTyped(json, false);
}

export function UserDetailsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailsUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'],
        'profilePicture': json['profile_picture'] == null ? undefined : json['profile_picture'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UserDetailsUpdateToJSON(json: any): UserDetailsUpdate {
    return UserDetailsUpdateToJSONTyped(json, false);
}

export function UserDetailsUpdateToJSONTyped(value?: UserDetailsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'profile_picture': value['profilePicture'],
        'description': value['description'],
    };
}

