name: "Reusable Tests"

on:
    workflow_call:
        inputs:
            ref:
                description: "Git ref to check out before running tests"
                required: false
                type: string

jobs:
    unit-tests:
        name: "Unit Tests"
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:7-alpine
                ports:
                    - 6379:6379

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v6
              with:
                  ref: ${{ inputs.ref }}
              # Must be first, so that GH actions finds our local actions!
              
            - name: "Set up CI environment"
              uses: ./.github/actions/setup-ci-environment
              with:
                  setup-node: "true"

            - name: "Install Python dependencies"
              run: poetry install --no-interaction --no-root

            - name: "Run unit tests"
              run: poetry run python src/manage.py test
